INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Evan','Ross','Port Washington');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Damian','Lopez','Half Moon Bay');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('William','Delacruz','Sharon');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Jamalia','Carr','Sheridan');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Dexter','Norman','Indio');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Xanthus','Bright','Bethany');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Anne','Moss','Newton');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Sopoline','Reilly','North Tonawanda');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Casey','Flores','Dover');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Carl','Norman','Waco');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Adara','Witt','Racine');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Oliver','Cunningham','Enid');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Barrett','Christensen','Lodi');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Tyler','Mitchell','Odessa');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Paula','Terrell','Gardner');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Cara','Spears','Jenks');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Dara','Vaughan','Berlin');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Stephanie','Rollins','Sitka');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Karyn','Welch','Cape May');
INSERT INTO CUSTOMERS (NAME,SURNAME,CITY) VALUES ('Piper','Burke','Santa Monica');

INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Accounting','72','6429');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Advertising','99','7841');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Sales and Marketing','97','8437');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Human Resources','39','4324');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Accounting','66','6232');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Media Relations','12','7830');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Finances','41','3864');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Quality Assurance','46','3243');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Accounting','16','2989');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Customer Relations','62','2704');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Tech Support','2','8387');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Advertising','16','1016');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Customer Service','50','7733');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Altavista','Media Relations','78','8629');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Customer Relations','22','4636');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Accounting','64','9248');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Media Relations','71','4022');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Legal Department','33','6394');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Payroll','27','6648');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Accounting','87','3288');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Legal Department','61','3507');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Customer Relations','49','8258');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Tech Support','29','7279');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Human Resources','44','7409');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Customer Relations','14','6500');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Adobe','Asset Management','66','3155');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Advertising','9','3466');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Quality Assurance','55','7914');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Altavista','Human Resources','40','5678');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Adobe','Tech Support','75','8368');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Payroll','45','6401');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Adobe','Asset Management','46','3860');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Customer Relations','88','1158');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Quality Assurance','22','5713');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Quality Assurance','49','7687');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Human Resources','16','1617');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Quality Assurance','57','3727');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Payroll','28','9084');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Tech Support','62','4048');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Altavista','Accounting','5','7411');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Sales and Marketing','40','3301');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Adobe','Public Relations','81','2811');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Asset Management','22','7236');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Advertising','30','8590');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Accounting','57','3652');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Customer Service','46','7436');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Payroll','38','9477');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Borland','Accounting','8','1169');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Borland','Human Resources','98','8921');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Customer Relations','19','3099');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Customer Service','73','3844');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Human Resources','47','2972');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Advertising','3','5857');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Media Relations','3','2618');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Legal Department','70','6708');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Human Resources','60','6073');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Tech Support','56','2383');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Customer Relations','66','1399');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Accounting','28','8357');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Quality Assurance','15','7373');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Legal Department','39','2746');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Customer Relations','45','9507');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Human Resources','83','8250');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Human Resources','78','7518');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Public Relations','50','5632');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Microsoft','Sales and Marketing','8','2623');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Sales and Marketing','7','5226');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Finances','61','5588');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Cakewalk','Accounting','13','6822');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Microsoft','Finances','24','9495');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Research and Development','89','4252');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Public Relations','37','9136');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Altavista','Public Relations','98','5181');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Finale','Quality Assurance','92','2941');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Borland','Customer Service','78','8376');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Finances','56','4549');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Yahoo','Sales and Marketing','67','8534');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Payroll','36','6160');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Finances','23','3304');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Microsoft','Accounting','80','7469');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Tech Support','97','3789');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Tech Support','59','5051');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Legal Department','79','2924');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Apple Systems','Media Relations','69','4814');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Google','Customer Service','9','9037');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Media Relations','88','6754');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Borland','Research and Development','9','2100');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Sibelius','Media Relations','79','6773');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Sales and Marketing','89','4724');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Borland','Public Relations','55','4992');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Microsoft','Advertising','86','5219');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Sales and Marketing','46','7903');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Tech Support','54','4449');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Customer Relations','34','3459');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Adobe','Customer Service','51','3277');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lavasoft','Sales and Marketing','58','1879');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Advertising','89','8325');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Macromedia','Public Relations','8','5664');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Lycos','Asset Management','9','6744');
INSERT INTO PRODUCTS (name,description,price,stock) VALUES ('Chami','Accounting','99','7782');

INSERT INTO BILLS (customerid,date,price) VALUES ('19','2012-01-27','89');
INSERT INTO BILLS (customerid,date,price) VALUES ('15','2011-01-30','78');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2011-08-22','11');
INSERT INTO BILLS (customerid,date,price) VALUES ('11','2012-01-02','45');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-11-13','4');
INSERT INTO BILLS (customerid,date,price) VALUES ('17','2011-09-13','61');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-09-04','33');
INSERT INTO BILLS (customerid,date,price) VALUES ('6','2012-01-05','68');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2011-09-08','71');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-03-27','86');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-10-23','56');
INSERT INTO BILLS (customerid,date,price) VALUES ('16','2011-07-22','46');
INSERT INTO BILLS (customerid,date,price) VALUES ('13','2011-07-04','30');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2010-12-02','63');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-03-06','64');
INSERT INTO BILLS (customerid,date,price) VALUES ('14','2010-12-17','35');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-08-23','53');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2011-04-10','63');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2010-11-25','73');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2010-11-28','90');
INSERT INTO BILLS (customerid,date,price) VALUES ('15','2010-12-17','96');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-07-03','26');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-10-08','83');
INSERT INTO BILLS (customerid,date,price) VALUES ('18','2011-04-23','69');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-02-21','41');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-03-07','8');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-12-21','39');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-09-26','62');
INSERT INTO BILLS (customerid,date,price) VALUES ('13','2011-10-06','61');
INSERT INTO BILLS (customerid,date,price) VALUES ('4','2011-02-26','4');
INSERT INTO BILLS (customerid,date,price) VALUES ('4','2011-11-23','98');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-10-15','76');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2012-01-13','52');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-10-03','13');
INSERT INTO BILLS (customerid,date,price) VALUES ('4','2011-04-05','45');
INSERT INTO BILLS (customerid,date,price) VALUES ('0','2011-06-13','100');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2012-01-26','51');
INSERT INTO BILLS (customerid,date,price) VALUES ('4','2011-08-05','69');
INSERT INTO BILLS (customerid,date,price) VALUES ('6','2011-01-30','18');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-09-23','88');
INSERT INTO BILLS (customerid,date,price) VALUES ('11','2011-12-08','90');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-06-09','53');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-10-11','49');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2011-06-19','96');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2012-02-02','38');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-07-12','33');
INSERT INTO BILLS (customerid,date,price) VALUES ('6','2011-04-26','38');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2011-01-07','84');
INSERT INTO BILLS (customerid,date,price) VALUES ('17','2012-02-04','46');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-04-07','13');
INSERT INTO BILLS (customerid,date,price) VALUES ('18','2011-11-24','98');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2011-01-01','31');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-08-20','36');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-03-03','82');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-01-05','36');
INSERT INTO BILLS (customerid,date,price) VALUES ('13','2011-12-09','11');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2012-02-01','65');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-09-18','54');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2011-05-28','78');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-05-09','23');
INSERT INTO BILLS (customerid,date,price) VALUES ('2','2010-12-06','49');
INSERT INTO BILLS (customerid,date,price) VALUES ('11','2011-11-10','50');
INSERT INTO BILLS (customerid,date,price) VALUES ('17','2010-12-05','64');
INSERT INTO BILLS (customerid,date,price) VALUES ('6','2011-06-22','75');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2011-09-01','29');
INSERT INTO BILLS (customerid,date,price) VALUES ('17','2012-01-16','100');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-08-10','98');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-01-24','74');
INSERT INTO BILLS (customerid,date,price) VALUES ('6','2011-05-06','29');
INSERT INTO BILLS (customerid,date,price) VALUES ('11','2011-04-24','88');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-06-28','25');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-08-07','89');
INSERT INTO BILLS (customerid,date,price) VALUES ('17','2011-03-02','62');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2011-01-16','3');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-10-03','91');
INSERT INTO BILLS (customerid,date,price) VALUES ('5','2011-07-31','54');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-08-23','81');
INSERT INTO BILLS (customerid,date,price) VALUES ('0','2012-02-06','25');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2011-11-18','36');
INSERT INTO BILLS (customerid,date,price) VALUES ('19','2011-03-28','53');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-06-29','85');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-07-20','90');
INSERT INTO BILLS (customerid,date,price) VALUES ('16','2011-02-11','81');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-02-27','17');
INSERT INTO BILLS (customerid,date,price) VALUES ('1','2010-12-12','19');
INSERT INTO BILLS (customerid,date,price) VALUES ('0','2011-11-21','72');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2011-11-20','2');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-06-09','34');
INSERT INTO BILLS (customerid,date,price) VALUES ('12','2011-04-08','2');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-09-10','1');
INSERT INTO BILLS (customerid,date,price) VALUES ('18','2011-09-25','62');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2010-12-28','31');
INSERT INTO BILLS (customerid,date,price) VALUES ('8','2011-12-18','57');
INSERT INTO BILLS (customerid,date,price) VALUES ('10','2011-01-20','85');
INSERT INTO BILLS (customerid,date,price) VALUES ('18','2011-10-10','53');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-06-22','56');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2011-12-22','89');
INSERT INTO BILLS (customerid,date,price) VALUES ('9','2011-10-07','21');
INSERT INTO BILLS (customerid,date,price) VALUES ('13','2011-12-15','9');
INSERT INTO BILLS (customerid,date,price) VALUES ('7','2010-12-29','78');

INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('86','76','87');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('55','16','32');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('10','30','86');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('43','77','25');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('16','74','41');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('81','87','63');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('76','82','30');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('27','57','6');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('66','94','71');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('10','29','90');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('6','16','67');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('92','72','84');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('24','83','14');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('9','26','91');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('34','43','65');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('74','24','52');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('37','1','35');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('66','28','92');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('71','95','86');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('42','5','16');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('32','11','32');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('99','4','4');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('82','29','87');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('95','38','14');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('85','73','57');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('50','47','82');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('2','84','83');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('36','50','12');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('27','22','8');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('13','64','14');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('28','97','26');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('60','96','30');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('64','78','59');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('51','73','98');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('64','59','71');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('20','9','19');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('2','11','3');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('85','48','54');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('97','75','77');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('4','89','41');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('17','18','39');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('42','78','35');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('72','43','13');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('31','94','87');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('29','59','47');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('0','80','56');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('18','82','68');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','67','16');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('75','64','92');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('51','69','81');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('92','86','100');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('30','29','79');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('65','1','22');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('77','33','17');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('64','62','76');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('10','62','56');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('66','81','39');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('34','3','7');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('49','78','71');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('41','30','41');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('22','23','27');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','53','57');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('99','19','59');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','96','92');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('37','61','55');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('13','72','18');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('69','38','99');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('7','72','3');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('14','22','81');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('85','63','12');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('25','85','35');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('52','7','89');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('8','6','8');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('66','28','4');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('58','66','66');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('12','79','38');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('30','49','76');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('28','57','49');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('30','71','71');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('11','56','35');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('22','81','20');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('56','34','27');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('44','42','34');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('51','9','62');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('55','67','29');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','80','8');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('58','10','57');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('34','39','15');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('82','70','86');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('53','81','43');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('87','4','24');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('7','61','59');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('33','6','1');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('67','58','10');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('29','13','78');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('57','35','58');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('64','93','69');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','28','8');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('36','11','78');
INSERT INTO BILLS_LINES (billid,productid,price) VALUES ('21','64','60');
